//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Car_Inspection
{
    using System;
    using System.Collections.Generic;
    
    public partial class Inspection
    {
        public int Inspection_id { get; set; }
        public int CarID { get; set; }
        public int OfficerID { get; set; }
        public System.DateTime Inspection_date { get; set; }
        public string Result { get; set; }
    
        public virtual Car Car { get; set; }
        public virtual PoliceOfficer PoliceOfficer { get; set; }
    }
}
